### PR TITLE
Fix style issue in `docs/source/conf.py`

### PR DESCRIPTION
**Pull request by jakirkham**
Currently the version update script is introducing a style error (using single quotes instead of double quotes) in the versions in `docs/source/conf.py`. This fixes that issue

### CODE REVIEW

**Review by grlee77 — APPROVED** [review]
Thanks, LGTM

**Comment by jakirkham** [comment]
That Greg! 🙏

Also tested the `sed` command lines to confirm it was doing the right thing

Will check with OPS on reviewing next week

**Comment by jakirkham** [comment]
Thanks all! 🙏

**Pull request merged**
