### PR TITLE
parameterization of `filters` and `features` benchmarks (v2)

### PR DESCRIPTION
**Pull request by grlee77**
Update of #278 for branch-22.08 with minor additional fixes. I have tested this locally and it seems to be operating as expected.

### CODE REVIEW

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Looks like there are some conflicts. Could you please take a look at these @grlee77? 🙂

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
@gpucibot merge

**Comment by grlee77** [comment]
> Looks like there are some conflicts. Could you please take a look at these @grlee77? slightly_smiling_face

Resolved. should be good to go now. No point to wait on CI as it doesn't run these benchmarks.

**Comment by jakirkham** [comment]
Yeah it won't merge until CI passes. So we just need to wait unfortunately. On the bright side it should merge as soon as CI passes

**Pull request merged**
