### PR TITLE
Fix memory leak in deflate decoder

### PR DESCRIPTION
**Pull request by gigony**
I did a silly mistake in deflate decoder which caused a memory leak when loading the Deflate-compressed TIFF image.

This patch will free allocated memory in decode_deflate() method.

For the next steps to prevent this kind of errors:
- Make use of a safe pointer (smart pointer) or scoped deleter for 3rdparty library/internal memory allocation.
- Run unit/integration tests with memory sanitizer/tracker (e.g., valgrind/asan)

### CODE REVIEW

**Comment by quasiben** [comment]
rerun tests

**Comment by gigony** [comment]
Build aborted due to timeout:

https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci-v0.20/job/cucim/job/prb/job/cucim-gpu-test/CUDA=11.0,GPU_LABEL=gpu,OS=ubuntu16.04,PYTHON=3.7/55/console

```
Examining conflict for rapids-build-env libarchive libxml2 icu:  77%|███████▋  | 71/92 [20:48<05:27, 15.62s/it]
Examining conflict for rapids-build-env cucim:  77%|███████▋  | 71/92 [21:08<05:27, 15.62s/it]                 
Examining conflict for rapids-build-env cucim:  78%|███████▊  | 72/92 [21:08<05:39, 16.95s/it]
Build timed out (after 40 minutes). Marking the build as failed.
```

**Comment by jakirkham** [comment]
Yeah this came up on Slack as well. Wondering if this is just due to the fact that we haven't fully moved to the new RAPIDS version scheme. If so, then it might be worth focusing on getting PR ( https://github.com/rapidsai/cucim/pull/41 ) in first and working with AJ to get cuCIM updated to the new version scheme

**Comment by gigony** [comment]
this change merged by other PR.

#close

**Pull request closed without merging**
