### PR TITLE
benchmarks: avoid use of deprecated pandas API

### PR DESCRIPTION
**Pull request by grlee77**
The `append` method of `DataFrame` was deprecated in pandas 1.4.0. 

Here, we update to use `pandas.concat` instead ([as recommended](https://pandas.pydata.org/docs/whatsnew/v1.4.0.html#whatsnew-140-deprecations-frame-series-append))

### CODE REVIEW

**Review by gigony — APPROVED** [review]
Looks good to me!

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Is it alright if we move this to 22.08?

**Comment by grlee77** [comment]
Yes

**Comment by grlee77** [comment]
replaced by #339

**Pull request closed without merging**
