### PR TITLE
Use released cupy 9

### PR DESCRIPTION
**Pull request by quasiben**
cc @jakirkham

### CODE REVIEW

**Comment by jakirkham** [comment]
With PR ( https://github.com/rapidsai/integration/pull/205 ), RAPIDS now uses CuPy 9. Think there's still some more work going on to upgrade compilers and such. After those changes land, I think we can look at dropping the custom things we did here to get CI working, which should make this easier to maintain going forward

**Comment by jakirkham** [comment]
Looks like GCC 9 was added in PR ( https://github.com/rapidsai/gpuci-build-environment/pull/177 )

**Comment by jakirkham** [comment]
Trying to handle this and generally moving us over to the normal RAPIDS build process in PR ( https://github.com/rapidsai/cucim/pull/21 )

**Comment by quasiben** [comment]
closing in favor of https://github.com/rapidsai/cucim/pull/21

**Pull request closed without merging**
