### PR TITLE
Remove NumPy <2 pin

### PR DESCRIPTION
**Pull request by seberg**
This PR removes the NumPy<2 pin which is expected to work for
RAPIDS projects once CuPy 13.3.0 is released (CuPy 13.2.0 had
some issues preventing the use with NumPy 2).

### CODE REVIEW

**Comment by jakirkham** [comment]
Now that CuPy 13.3.0 is out. Marking this ready for review

Merged in `branch-24.10` latest to pickup the fixes in PR: https://github.com/rapidsai/cucim/pull/764

**Comment by jakirkham** [comment]
Looks like the wheels had two test failures [in CI]( https://github.com/rapidsai/cucim/actions/runs/10513951295/job/29131099665?pr=762#step:8:620 ):

```python
FAILED python/cucim/src/cucim/skimage/color/tests/test_colorconv.py::test_gray2rgba_alpha_fail_cast[-1-uint8] - OverflowError: Python integer -1 out of bounds for uint8
FAILED python/cucim/src/cucim/skimage/color/tests/test_colorconv.py::test_gray2rgba_alpha_fail_cast[300-int8] - OverflowError: Python integer 300 out of bounds for int8
```

Conda doesn't have the same issue, but am seeing NumPy downgraded to there. So we are likely missing something there too

**Comment by jakirkham** [comment]
So Conda downgrades NumPy because

1. Conda-forge rebuilt scikit-image 0.24.0 with NumPy 2: https://github.com/conda-forge/scikit-image-feedstock/pull/110
2. Currently we only support scikit-image 0.23.x: https://github.com/rapidsai/cucim/issues/768

Addressing either of these would fix the issue

**Comment by seberg** [comment]
So this failure is now with NumPy 2.1, it seems pretty harmless, I pushed a potential fix, but would be good if @grlee77 can have a quick look if that seems good.

**Review by jameslamb — APPROVED** [review]
Packaging changes look ok to me. I poked around and don't see any other uses of `numpy` that were missed.


Just one question... have we double-checked that the assumptions here hold for both the NumPy 1.x and 2.x ABI?

https://github.com/rapidsai/cucim/blob/de6bfbb444acca44ef1c35846be7f53fdd70de6a/cpp/include/cucim/memory/dlpack.h#L33

Are there new-in-NumPy-2.x datatypes that need to be added there?

**Review by grlee77 — APPROVED** [review]
Thanks, @seberg. The compatibility change looks good to me

**Review by jakirkham — CHANGES_REQUESTED** [review]
Thanks all! 🙏

The changes look good here

We do need to update scikit-image, which is being done in PR: https://github.com/rapidsai/cucim/pull/769

So marking as requests changes and adding "DO NOT MERGE" until that PR is in

Once that PR is in will merge in the latest upstream branch here to rerun CI and confirm that we have fixed the Conda NumPy 1 downgrade issue mentioned above. Then validate the CI logs to make sure we are getting NumPy 2

Assuming all of that goes well. We can merge after

**Comment by jakirkham** [comment]
PR ( https://github.com/rapidsai/cucim/pull/769 ) was just merged

Have resolved conflicts (as `numpy` & `scikit-image` dependencies were on adjacent lines in come cases)

CI is now running

**Review by jakirkham — APPROVED** [review]
Ok can now see NumPy 2 in [CI testing of conda packages]( https://github.com/rapidsai/cucim/actions/runs/10517107340/job/29140941039?pr=762#step:7:368 ) and it remains through later updates

```
numpy                     2.1.0           py311hed25524_0    conda-forge
```

Approving now that this issue is cleared up

**Comment by jakirkham** [comment]
Thanks all! 🙏

**Pull request merged**
