### PR TITLE
Inform `setuptools` that `Extensions` are included

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/rapidsai/cucim/issues/641

As `setuptools`/`pip`/`wheel` will mark our package as pure (even though we put an extension module into it), make sure it doesn't by informing `setuptools` that `Extensions` are contained within. This should ensure that are wheels include the Python minor version they were built for.

### CODE REVIEW

**Comment by jakirkham** [comment]
This works! 🎉 

Final name [from CI]( https://github.com/rapidsai/cucim/actions/runs/7027516742/job/19122056172?pr=643#step:9:3607 ):

```
./cucim_cu11-23.12.0a21-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
```

**Review by grlee77 — APPROVED** [review]
Thanks, John. This looks good! I guess this may be preferable to renaming after the fact as in #644.

**Comment by jakirkham** [comment]
Based on offline discussion, we decided to go with PR ( https://github.com/rapidsai/cucim/pull/644 ) as it is a publicly documented API that is most consistent with how the build works

Longer term we might want to use `scikit-build` ( https://github.com/rapidsai/cucim/issues/645 ), which would make this unnecessary

**Review by raydouglass — APPROVED** [review]

**Review by bdice — APPROVED** [review]

**Review by vyasr — APPROVED** [review]

**Review by vyasr — CHANGES_REQUESTED** [review]
To unblock the release, can we also add (or symlink) the license into python/cucim?

**Comment by jakirkham** [comment]
Good catch. Went ahead and symlinked both and updated `pyproject.toml` to list both

**Review by raydouglass — APPROVED** [review]

**Pull request merged**
