### PR TITLE
Update run script for local builds

### PR DESCRIPTION
**Pull request by gigony**
- Update `run` script to download GDS from public package (cufile.h is needed to build it locally)
  - Update CMakeLists.txt accordingly
  - GDS is still disabled (need to use GDS Conda package and verify it before enabling GDS)
- Update CUDA EULA (which include libcufile)
- Add dependency to `yasm` which is needed for building libjpeg-turbo
- Clear CMakeCathe.txt and existing .so files to build with the updated options
- Minor code change (unnecessarily std::move which degrade performance).
- Add changelog for `v0.18.3` and update the release date of v0.19.0 to 4/19/2021

Verified with a fresh system that https://github.com/rapidsai/cucim/blob/branch-0.20/CONTRIBUTING.md#script-to-build-cucim-from-source is working. (Previously it didn't work due to `yasm` dependency).

### CODE REVIEW

**Comment by gigony** [comment]
Hi @raydouglass 

Since we didn't tag v0.19.0 yet and VERSION files in branch-0.20 are still referring to 0.19.0, would it make sense to fast-forward branch-0.19 branch to branch-0.20 instead of creating a PR with the same commits to branch-0.19?

If branch-0.19 is not available for fast-forwarding, I can create a PR with the duplicate commits in branch-0.20 for branch-0.19.

**Comment by gigony** [comment]
I see some build error because python build is using the existing libcucim conda package but libcucim code in C++ is also changed in the PR. 
: https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci-v0.20/job/cucim/job/prb/job/cucim-cpu-python-build/CUDA=11.0,PYTHON=3.7/17/console line 704

Wonder I need to push PRs for libcucim([core lib code](https://github.com/rapidsai/cucim/pull/12/files#diff-523c548204c12cab58d81badea5c01cdaddcebf87c22534184d23a8b4ee2c0a6R108)) and cucim ([pybind11&python code](https://github.com/rapidsai/cucim/pull/12/files#diff-7b42e1ab0bc6b1b9deb7c1557055cba6b57685d60558b521063b684208352c14R63)) separately.

**Review by ajschmidt8 — APPROVED** [review]
Approving `ops-codeowner` file changes

**Comment by gigony** [comment]
It seems that it always using libcucim from nightly build

https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci-v0.20/job/cucim/job/prb/job/cucim-cpu-python-build/CUDA=11.0,PYTHON=3.7/18/console

```
18:08:35     libcucim:         0.19.0a210416-cuda11.0_g6cfdbfb_9 rapidsai-nightly  
```

@ajschmidt8 Do you have any idea on that? How could we handle the situation?

**Comment by gigony** [comment]
I found that libcucim's built package is available at `${WORKSPACE}/ci/artifacts/cucim/cpu/.conda-bld` when cucim is built so I updated `build.sh` for cpu cucim build through https://github.com/rapidsai/cucim/pull/12/commits/cd3ae09578407c401515febff2cca0316f57211a, to use cpu libcucim build. 
This approach was already made in GPU build (https://github.com/rapidsai/cucim/blob/branch-0.20/ci/gpu/build.sh#L61).

This PR is passing now.

@quasiben, please help review the change.
This change also requires an approval from @jakirkham (rapidsai/cucim-cpp-codeowners) so I don't know how to merge it without @jakirkham's help.

**Review by quasiben — APPROVED** [review]
Thanks @gigony I'll port these changes back to 0.19 after being merged

**Pull request merged**
