### PR TITLE
update pypi CHANGELOG.md for releases 22.08.00 and 22.08.01

### PR DESCRIPTION
**Pull request by grlee77**

### CODE REVIEW

**Comment by jakirkham** [comment]
Think this got resolved by the forward-merge PR ( https://github.com/rapidsai/cucim/pull/403 ), but please double check

**Comment by grlee77** [comment]
That content is mostly the same, but this is a second copy of the CHANGELOG.md that is under the `python/cucim` folder and gets included in the `long_description` in `setup.py` so that it shows up on PyPI. I didn't realize we even had this second changelog when I did the 22.08.00 release, so it was not updated at that time. That is why both 22.08.00 and 22.08.01 changes are both here.

It seems we could migrate to just a single file going forward. (as for the README issue you recently raised in #397)

**Comment by grlee77** [comment]
This is where these second copies are used:
https://github.com/rapidsai/cucim/blob/90fc72aa149b2bd2fa89622e2fb5f0ab5010b596/python/cucim/setup.py#L33-L37

**Comment by jakirkham** [comment]
Oh missed that. Thanks for clarifying Greg 🙏

Yeah think tracking these duplicates down and coming up with a way to consolidate should save us additional maintenance work in the future

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
@gpucibot merge

**Comment by jakirkham** [comment]
Thanks Greg! 🙏

**Pull request merged**
