### PR TITLE
Revert "Allow CuPy 11"

### PR DESCRIPTION
**Pull request by galipremsagar**
Reverts rapidsai/cucim#357

### CODE REVIEW

**Comment by quasiben** [comment]
I think cuCIM wants to use CuPy 11 even though RAPIDS need to exclude it for now.  This has happened in the past where cuCIM needs to specifically add CuPy 11 to the CI infra to properly test

**Review by ajschmidt8 — APPROVED** [review]

**Comment by ajschmidt8** [comment]
> I think cuCIM wants to use CuPy 11 even though RAPIDS need to exclude it for now. This has happened in the past where cuCIM needs to specifically add CuPy 11 to the CI infra to properly test

@quasiben, will `cucim` be using CuPy features that are exclusively in CuPy 11? If so, I think this will cause issues with the `rapids` package on Anaconda ([src](https://github.com/rapidsai/integration/blob/53e92859fc0a5d6c84d5fc50bbf171731ad05d74/conda/recipes/rapids/meta.yaml#L39-L64)) if `cucim` needs CuPy 11, but the rest of RAPIDS can only use CuPy 10.

**Comment by jakirkham** [comment]
Discussed with @grlee77, we are going to bump the feature that needed CuPy 11 to 22.10. So sticking to CuPy 10 for 22.08 should be ok for us

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
@gpucibot merge

**Comment by jakirkham** [comment]
Thanks all! 🙏

**Pull request merged**
