### PR TITLE
Enable all tests for `arm` jobs

### PR DESCRIPTION
**Pull request by galipremsagar**
This PR enables running all tests in `arm` jobs

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks Prem! 🙏

There's a few known test failures in issue: https://github.com/rapidsai/cucim/issues/473

**Comment by jakirkham** [comment]
Should we delete this file (if it is unused)?

https://github.com/rapidsai/cucim/blob/eee3e4c3ae6521b532978f20e7083a5a3ea8287d/ci/wheel_smoke_test.py#L1-L3

**Review by raydouglass — APPROVED** [review]

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks all! 🙏

**Pull request merged**
