### PR TITLE
Update cupy dependency

### PR DESCRIPTION
**Pull request by vyasr**
Switch to requiring cupy 12

### CODE REVIEW

**Comment by jakirkham** [comment]
Do we want to update the Conda recipe too?

https://github.com/rapidsai/cucim/blob/2207a690eff2bef2d084233ce20318ddc9547642/conda/recipes/cucim/meta.yaml#L48

**Review by AyodeAwe — APPROVED** [review]

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
General question. In a few places (like in cuCIM) we had an upper bound. Do we want that going forward or are we wanting to drop that?

**Comment by vyasr** [comment]
We decided to drop, see https://github.com/rapidsai/cugraph/pull/3539#pullrequestreview-1412087488

**Pull request merged**
