### PR TITLE
Merge docs and add links

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/rapidsai/cucim/issues/397
Fixes https://github.com/rapidsai/cucim/issues/395

* Symlinks top-level README and CHANGELOG into `python/cucim/`
* Adds links to the developer page on PyPI and Anaconda
* Also adds links for docs, source, etc.

cc @grlee77 @gigony

### CODE REVIEW

**Review by gigony — APPROVED** [review]
Looks good to me.
Thank you John!
Now we don't need to maintain README/CHANGELOG.md for PyPI package :)

**Comment by jakirkham** [comment]
Also confirmed that running `python setup.py sdist` resolved the symlinks correctly to include the `README.md` and the `CHANGELOG.md` in the `sdist` produced.

With `python setup.py bdist_wheel`, this content gets copied into the `METADATA` file included in the `.whl`.

**Review by jolorunyomi — APPROVED** [review]

**Comment by jakirkham** [comment]
rerun tests

([CI had some issue]( https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cucim/job/prb/job/cucim-gpu-test/CUDA=11.2,GPU_LABEL=driver-495,LINUX_VER=ubuntu18.04,PYTHON=3.9/423/console ) pulling from the repo)

**Comment by jakirkham** [comment]
@gpucibot merge

**Pull request merged**
