### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by HesAnEasyCoder**
Incorporated link to developer page: https://developer.nvidia.com/multidimensional-image-processing.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
add to allowlist

**Comment by raydouglass** [comment]
add to allowlist

**Comment by jakirkham** [comment]
@gpucibot merge

**Comment by jakirkham** [comment]
Thanks! 🙏

**Pull request merged**
