### PR TITLE
Add cucim.skimage.feature.match_descriptors

### LINKED ISSUE #193: [FEA] gpu enabled match_descriptors
I've heard from some folks that they would like to see an implementation of [match_descriptors](https://scikit-image.org/docs/dev/api/skimage.feature.html?highlight=match_descriptor#skimage.feature.match_descriptors) in cuCIM.  This might be challenging as I don't think [cdist](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html) is implemented in CuPy yet.

xref: https://github.com/scikit-image/scikit-image/blob/main/skimage/feature/match.py#L5

### PR DESCRIPTION
**Pull request by grlee77**
closes #193

This PR adds `cucim.skimage.feature.match_descriptors`. It is a very straightforward adaptation of the scikit-image code, only substituting numpy->cupy. The only differences of note are:
- when new enough CuPy and pylibraft are not available it warns and falls back to `cdist` on the CPU
- test cases involving BRIEF temporarily involve round trip to the host until we implement BRIEF here (looks not too hard)

This PR also removes the deprecated `masked_register_translation` and `register_translation` (these were moved to cucim.skimage.registration.phase_cross_correlation`) from the `feature` module. Removing those was missed when previously updating the API here to match scikit-image 0.19.

### CODE REVIEW

**Comment by grlee77** [comment]
The acceleration provided here will depend on the number and size of the descriptors. Running scikit-image's SIFT on the small `astronaut` image results in 1234 descriptors each of size 128. For that size of input, the relative acceleration on the GPU is quite good.

When cross_check=False, max_distance=np.inf, max_ratio = 1.0
**Acceleration = 333.44040448425943**

When cross_check=True, max_distance=np.inf, max_ratio = 1.0
**Acceleration = 138.47554030822292**

When cross_check=False, max_distance=100.0, max_ratio < 1.0
**Acceleration = 58.34578386444441**

In the latter two cases there are progressively more logical comparisons and indexing operations which end up reducing the overall acceleration factor as compared to the first case without any additional checks.

**Comment by jakirkham** [comment]
Moved to 22.10

There's not a project board for this yet. So moved to feature planning for now. Can update that later

**Comment by ajschmidt8** [comment]
Removing `ops-codeowners` from the required reviews since it doesn't seem there are any file changes that we're responsible for. Feel free to add us back if necessary.

**Comment by jakirkham** [comment]
Yeah I accidentally got 21.10 the first time 🤦‍♂️ Sorry for the noise 😞

Should be fixed now 🍀

**Comment by grlee77** [comment]
This PR now has that same issue we saw previously where the `distance_transform_edt` import fails even though the files are in this branch.

```
src/cucim/core/operations/morphology/tests/test_distance_transform.py:8: in <module>
    from cucim.core.operations.morphology import distance_transform_edt
E   ModuleNotFoundError: No module named 'cucim.core.operations.morphology'
```


I need to look into how we are doing the install when testing on CI. Perhaps the files are there during build but are getting omitted somehow during the package install stage?

**Comment by grlee77** [comment]
rerun tests

**Review by gigony — APPROVED** [review]
Looks good to me. Thank you Greg!

**Comment by gigony** [comment]
@gpucibot merge

**Pull request merged**
