### PR TITLE
Check compression method used in the image (#17)

### PR DESCRIPTION
**Pull request by gigony**
SVS format is not supported for now but we loosen the restriction by
delegating its process to libtiff's TIFFRGBAImageGet() method.
cuCIM assumes that only one image with Subfile Type(=0) is available in
the image file but apparently, some SVS files have also only one Subfile
Type with zero so bypassing the check.

This patch explicitly checks SVS format and compression methods and
raises an exception if the given file doesn't match the criteria.
Once SVS format is supported, those changes need to be updated to not
raise exceptions for SVS files.

Resolves: #17

### CODE REVIEW

**Review by quasiben — APPROVED** [review]

**Comment by quasiben** [comment]
@gigony can this wait until Monday to get merged ?  If not, we can ask ops to merge for us while John is out on PTO

**Comment by gigony** [comment]
> @gigony can this wait until Monday to get merged ? If not, we can ask ops to merge for us while John is out on PTO

Sure, it is absolutely okay to be merged later. Thank you!

**Comment by jakirkham** [comment]
rerun tests

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
@gpucibot merge

**Pull request merged**
