### PR TITLE
update docs theme to pydata-sphinx-theme

### PR DESCRIPTION
**Pull request by quasiben**
Fixes https://github.com/rapidsai/cucim/issues/133

### CODE REVIEW

**Review by jakirkham — APPROVED** [review]

**Comment by quasiben** [comment]
rerun tests

**Comment by quasiben** [comment]
I'm not sure why this is segfaulting on import:

> ci/gpu/build.sh: line 91:  1659 Segmentation fault      (core dumped) python -c 'import cucim'

https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci-cuda115/job/cucim/job/prb/job/cucim-gpu-test/CUDA=11.5,GPU_LABEL=cuda115,LINUX_VER=centos7,PYTHON=3.8/5/console#L1,892

**Comment by quasiben** [comment]
rerun tests

**Comment by jakirkham** [comment]
I think 11.5 just fails currently. So we can ignore that for now

**Comment by jakirkham** [comment]
@gpucibot merge

**Pull request merged**
