### PR TITLE
Add benchmarks for scikit-image functions introduced in 22.08

### PR DESCRIPTION
**Pull request by grlee77**
This PR adds benchmarks for a few of the recently introduced functions.

It also uses more realistic nD label object generation for the segmentation benchmarks.

### CODE REVIEW

**Comment by grlee77** [comment]
no need to immediately review this for the 22.08 release since we don't ship the benchmark scripts

**Review by gigony — APPROVED** [review]
Thanks Greg!
Looks good to me.

**Comment by gigony** [comment]
@gpucibot merge

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
@gpucibot merge

**Pull request merged**
