### PR TITLE
Merge branch-22.08 into branch-22.10 [skip gpuci]

### PR DESCRIPTION
**Pull request by jakirkham**
Addresses the forward merger conflict seen in PR ( https://github.com/rapidsai/cucim/pull/351 ).

### CODE REVIEW

**Comment by grlee77** [comment]
It looks okay to me, but not sure why the test is failing?

[This error](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cucim/job/prb/job/cucim-gpu-test/CUDA=11.2,GPU_LABEL=driver-495,LINUX_VER=ubuntu18.04,PYTHON=3.9/362/testReport/junit/(root)/(empty)/src_cucim_core_operations_morphology_tests_test_distance_transform/):
```
E   ModuleNotFoundError: No module named 'cucim.core.operations.morphology'
```
doesn't make sense to me because the files for that are in this PR as expected. Is it possible a prior build of cucim is getting cached?

**Review by grlee77 — APPROVED** [review]
It looks okay to me, but there are a handful of CI failures.

**Comment by jakirkham** [comment]
rerun tests

**Comment by jakirkham** [comment]
rerun tests

**Review by ajschmidt8 — APPROVED** [review]
This will need to be admin merged with a merge commit instead of a squash commit once CI is passing.

**Comment by jakirkham** [comment]
Interesting. We keep seeing CI failures here due to missing files, which are actually there. Last night it was only 1 job failure (after rerunning). Now it is 2. Not sure why this is happening.

**Comment by jakirkham** [comment]
Still got a failure. Going to disable CI and go ahead as we haven't seen this elsewhere. If it starts cropping up in other places, we can take a closer look.

**Comment by jakirkham** [comment]
@gpucibot merge

**Comment by jakirkham** [comment]
(asking offline for help)

**Comment by ajschmidt8** [comment]
I manually pushed https://github.com/rapidsai/cucim/commit/2121f75c3a4820cc9db8749d5ea10805dc6973a4, which closed #351. Therefore we can close this PR now.

**Comment by jakirkham** [comment]
Thanks AJ! 🙏

**Pull request closed without merging**
