### PR TITLE
skip CMake 3.30.0, require CMake >=3.26.4

### PR DESCRIPTION
**Pull request by jameslamb**
## Description

Contributes to https://github.com/rapidsai/build-planning/issues/80

Adds constraints to avoid pulling in CMake 3.30.0, for the reasons described in that issue.

## Notes for Reviewers

Most of the rest of RAPIDS is using `cmake >=3.26.4`... but I didn't change the floor here to match that, because I didn't know if it was intentional that `cucim` allows a wider range of `cmake` versions.

Let me know if you'd prefer I bump the `cmake` minimum version to `3.26.4` as part of this.

### CODE REVIEW

**Review by bdice — CHANGES_REQUESTED** [review]
Can we update this repo to use the same pinnings as the rest of RAPIDS? Something like `>=3.26.4,!=3.30.0`.

**Comment by jameslamb** [comment]
> Can we update this repo to use the same pinnings as the rest of RAPIDS?

Sure! Like I mentioned in the description, I wasn't sure if this repo was intentionally using a more permissive range than others.

Just pushed commits moving the floor to `3.26.4` and updated the PR title.

**Review by bdice — APPROVED** [review]
Thanks. I think it was an oversight that we had not kept CMake pinnings aligned with the rest of RAPIDS in past CMake update migrations.

**Review by KyleFromNVIDIA — APPROVED** [review]

**Review by grlee77 — APPROVED** [review]
Thanks for updating the CMake pinning. I don't think we had any specific requirement to support older versions, so the update here seems fine.

**Pull request merged**
