### PR TITLE
Allow numpy 1.24.

### PR DESCRIPTION
**Pull request by bdice**
This removes the upper bound on `numpy<1.24` to allow newer NumPy versions.

### CODE REVIEW

**Comment by grlee77** [comment]
Thanks @bdice, it looks good. Opened #564 to resolve the unrelated test failures

**Comment by bdice** [comment]
Great. Once #564 is merged, feel free to update this PR with `branch-23.06` and merge.

**Comment by jakirkham** [comment]
Thanks all! 🙏

**Pull request merged**
