### PR TITLE
Remove code needed to support Python < 3.9 and apply ruff's pyupgrade rules

### PR DESCRIPTION
**Pull request by grlee77**
`math.prod` was added in Python 3.8
`math.lcm` was added in Python 3.9

`pyproject.toml` was updated to have `ruff` also check [pyupgrade rules](https://docs.astral.sh/ruff/rules/#pyupgrade-up)

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks Greg! 🙏

Seeing one test failure in [this CI job]( https://github.com/rapidsai/cucim/actions/runs/8716002781/job/23909243290?pr=725#step:8:495 ):

```python
_ test_read_random_region_cpu_memleak[testimg_tiff_stripe_4096x4096_256_deflate] _
[gw6] linux -- Python 3.9.19 /pyenv/versions/3.9.19/bin/python
python/cucim/tests/performance/clara/test_read_region_memory_usage.py:100: in test_read_random_region_cpu_memleak
    assert mem_usage_history[-1] - mem_usage_history[1] < iteration * 100
E   assert (828035072 - 826982400) < (1000 * 100)
```

**Comment by grlee77** [comment]
> Seeing one test failure in [this CI job](https://github.com/rapidsai/cucim/actions/runs/8716002781/job/23909243290?pr=725#step:8:495):

Definitely looks unrelated to this MR. The failure was not reproduced when I re-ran the job.

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Greg! 🙏

**Pull request merged**
