### PR TITLE
complete parametrization of cucim.skimage benchmarks

### PR DESCRIPTION
**Pull request by grlee77**
This PR expands the approach of #322 to the remaining `cucim.skimage` benchmarks as well

This PR is built on top of a few other open benchmarking PRs, so please review and merge those first: (#322, #323, #290)

### CODE REVIEW

**Comment by jakirkham** [comment]
Looks like there are some conflicts here. Could you please resolve these @grlee77? 🙂

**Comment by grlee77** [comment]
Fixed conflicts, added a `requirements-bench.txt` as discussed in https://github.com/rapidsai/cucim/pull/323#pullrequestreview-1051664651.

**Comment by grlee77** [comment]
might have to resolve conflicts again if #323 is merged (although all changes from #323 are also present here if you want to merge only this one)

**Comment by jakirkham** [comment]
Would it make sense to close that PR then?

**Comment by grlee77** [comment]
Yeah, it is fine to close that one.

**Comment by grlee77** [comment]
Just fixed a few new conflicts here. Should be good to go now

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
@gpucibot merge

**Comment by jakirkham** [comment]
Thanks Greg! 🙏

**Pull request merged**
