### PR TITLE
Update README.md [skip ci]

### PR DESCRIPTION
**Pull request by HesAnEasyCoder**
Incorporating latest blog that dropped 7/27.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by HesAnEasyCoder** [comment]
Adding latest blog to GitHub

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
@gpucibot merge

**Review by ajschmidt8 — APPROVED** [review]

**Comment by ajschmidt8** [comment]
okay to test

**Comment by jakirkham** [comment]
add to allowlist

**Pull request merged**
