### PR TITLE
Add Jupyter notebook for SVS Support

### PR DESCRIPTION
**Pull request by gigony**
- Update `notebooks/Welcome.ipynb`
- Add `notebooks/Supporting_Aperio_SVS_Format.ipynb` to show loading Aperio SVS images

### CODE REVIEW

**Comment by jakirkham** [comment]
rerun tests

**Comment by jakirkham** [comment]
There's some commented code in the notebook like

```python
#         start_loc_data = [(sx, sy)
...
```

Should we drop that?

**Comment by gigony** [comment]
> There's some commented code in the notebook like
> 
> ```python
> #         start_loc_data = [(sx, sy)
> ...
> ```
> 
> Should we drop that?
> 
> Edit: Also wonder if we should break the `Experiment Code` section out into a script

Good idea! Thank you for the suggestion. Moved as scripts and removed unnecessary comments.

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
@gpucibot merge

**Pull request merged**
