### PR TITLE
Do not suggest use of black in contributing guide

### PR DESCRIPTION
**Pull request by grlee77**
I think we still have black intentionally disabled here (to make comparison to upstream scikit-image code easier).

### CODE REVIEW

**Review by gigony — APPROVED** [review]
Looks good to me!

**Comment by jakirkham** [comment]
rerun tests

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
It would be good to fix `black` support in the future, but this seems fine for now

**Comment by jakirkham** [comment]
@gpucibot merge

**Pull request merged**
