### PR TITLE
Update release script [skip-ci]

### PR DESCRIPTION
**Pull request by raydouglass**
Update the release script to take a parameter with the new version instead of calculating the new version.

### CODE REVIEW

**Review by dillon-cullinan — APPROVED** [review]

**Review by ajschmidt8 — APPROVED** [review]

**Review by gigony — APPROVED** [review]
Thanks @jakirkham! Looks good for the release script side!  I would update the following logic in the follow-up PRs.

- https://github.com/rapidsai/cucim/blob/branch-0.20/ci/release/update-version.sh#L53
- https://github.com/rapidsai/cucim/blob/branch-0.20/run#L972

**Comment by jakirkham** [comment]
Thanks Gigon. Makes sense. Let's look at that next 🙂

**Review by jakirkham — APPROVED** [review]

**Comment by raydouglass** [comment]
@gpucibot merge

**Comment by jakirkham** [comment]
Follow up changes mentioned above in PR ( https://github.com/rapidsai/cucim/pull/32 )

**Pull request merged**
